#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2006 Carlos Sobrinho

START=60

PROG=/bin/spot_inspection
NAME=spot_inspection


start()
{
	if [ $(pgrep -f spot_inspection |wc -l) = "1" ]
	then
		kill $(pidof spot_inspection)
	fi
	/bin/spot_inspection
}

stop()
{
	kill $(pidof spot_inspection)
}
